import { User, Event, Chat, Message } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'Nguyen Van A',
    email: 'nguyenvana@example.com',
    image: 'https://kimurakami.com/cdn/shop/files/Mens-Japanese-Kimono.jpg?v=1719471298',
    bio: 'Love reading manga and drinking coffee',
    age: 25,
    gender: 'male',
    hobbies: ['1', '2', '8'],
    preferredLocations: ['1', '2'],
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Tran Thi B',
    email: 'tranthib@example.com',
    image: 'https://kimurakami.com/cdn/shop/files/Mens-Japanese-Kimono.jpg?v=1719471298',
    bio: 'Photographer and travel enthusiast',
    age: 28,
    gender: 'female',
    hobbies: ['6', '11', '5'],
    preferredLocations: ['4', '5'],
    createdAt: '2024-01-20',
  },
  {
    id: '3',
    name: 'Le Van C',
    email: 'levanc@example.com',
    image: 'https://kimurakami.com/cdn/shop/files/Mens-Japanese-Kimono.jpg?v=1719471298',
    bio: 'Pickleball player looking for partners',
    age: 30,
    gender: 'male',
    hobbies: ['4', '9', '7'],
    preferredLocations: ['7', '8'],
    createdAt: '2024-02-01',
  },
  {
    id: '4',
    name: 'Pham Thi D',
    email: 'phamthid@example.com',
    image: 'https://kimurakami.com/cdn/shop/files/Mens-Japanese-Kimono.jpg?v=1719471298',
    bio: 'Yoga instructor and healthy cooking lover',
    age: 26,
    gender: 'female',
    hobbies: ['9', '7', '2'],
    preferredLocations: ['4', '6'],
    createdAt: '2024-02-10',
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: 'Manga Reading Meetup',
    description: 'Join us for a casual manga reading session at a cozy cafe',
    hostId: '1',
    hobbyId: '1',
    locationId: '1',
    date: '2024-12-15',
    time: '14:00',
    maxParticipants: 5,
    currentParticipants: ['1', '2'],
    status: 'open',
    createdAt: '2024-11-20',
  },
  {
    id: '2',
    title: 'Photography Walk in Shibuya',
    description: 'Explore Shibuya with your camera and capture amazing shots',
    hostId: '2',
    hobbyId: '6',
    locationId: '1',
    date: '2024-12-10',
    time: '10:00',
    maxParticipants: 8,
    currentParticipants: ['2', '3', '4'],
    status: 'open',
    createdAt: '2024-11-18',
  },
  {
    id: '3',
    title: 'Pickleball Tournament',
    description: 'Friendly pickleball matches for all skill levels',
    hostId: '3',
    hobbyId: '4',
    locationId: '7',
    date: '2024-12-12',
    time: '16:00',
    maxParticipants: 10,
    currentParticipants: ['3', '1'],
    status: 'open',
    createdAt: '2024-11-22',
  },
  {
    id: '4',
    title: 'Coffee Tasting Session',
    description: 'Discover different coffee flavors from around the world',
    hostId: '1',
    hobbyId: '2',
    locationId: '4',
    date: '2024-12-08',
    time: '15:30',
    maxParticipants: 6,
    currentParticipants: ['1', '4'],
    status: 'open',
    createdAt: '2024-11-25',
  },
  {
    id: '5',
    title: 'Yoga in the Park',
    description: 'Morning yoga session for relaxation and mindfulness',
    hostId: '4',
    hobbyId: '9',
    locationId: '5',
    date: '2024-12-14',
    time: '07:00',
    maxParticipants: 12,
    currentParticipants: ['4', '2', '3'],
    status: 'open',
    createdAt: '2024-11-23',
  },
];

export const MOCK_CHATS: Chat[] = [
  {
    id: '1',
    eventId: '1',
    participants: ['1', '2'],
    createdAt: '2024-11-21',
  },
  {
    id: '2',
    eventId: '2',
    participants: ['2', '3', '4'],
    createdAt: '2024-11-19',
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: '1',
    chatId: '1',
    senderId: '1',
    content: 'Hey! Looking forward to the manga meetup!',
    timestamp: '2024-11-21T10:30:00',
    read: true,
  },
  {
    id: '2',
    chatId: '1',
    senderId: '2',
    content: 'Me too! Have you read the latest chapter?',
    timestamp: '2024-11-21T10:35:00',
    read: true,
  },
  {
    id: '3',
    chatId: '2',
    senderId: '2',
    content: 'The weather looks perfect for our photography walk!',
    timestamp: '2024-11-22T14:20:00',
    read: false,
  },
];
